views:
  # Alters the pod view column layout. Uses GVR as key
  v1/pods:
    # Overrides default sort column
    sortColumn: AGE:asc
    columns:
      - NAME
      - READY|W
      - PF|W
      - STATUS
      - RESTARTS
      - AGE
      - NAMESPACE|WR 
      - IP|W
      - NODE|W
      - CPU|W 
      - '%CPU/R|W' 
      - '%CPU/L|W' 
      - MEM|W 
      - '%MEM/R|W' 
      - '%MEM/L|W' 

