"Display settings
set number
syntax on

"Search will be case sensitive if it contains an uppercase letter.
set smartcase

"Disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

"Set space as leader
nnoremap <SPACE> <Nop>
let mapleader=" "
